# INTERACTIVE_MODELS_PATH: "./weights"
INTERACTIVE_MODELS_PATH: "/playpen-raid/qinliu/models/model_1012_2021/iter_mask/pascal_hrnet18/001/checkpoints"
EXPS_PATH: "/playpen-raid/qinliu/models/model_1012_2021"

# Evaluation datasets
GRABCUT_PATH: "/playpen-raid/qinliu/data/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"

# Train datasets
SBD_PATH: "/playpen-raid/qinliu/data/SBD/dataset"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "/playpen-raid/qinliu/data/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./weights/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./weights/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./weights/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./weights/hrnetv2_w48_imagenet_pretrained.pth"
  MIT_B5: "./weights/mit_b5.pth"
  MIT_B3: "./weights/mit_b3.pth"
  MIT_B1: "./weights/mit_b1.pth"
  MIT_B0: "./weights/mit_b0.pth"